import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";



const talios = localFont({
  src: "./fonts/tallios-font/tallios.otf",
  variable: "--font-tallios",
  weight: "400",
  style: "normal",
});

const calama = localFont({
  src: "./fonts/Calama/Calama_new.ttf",
  variable: "--font-calama",
  weight: "400",
  style: "normal",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${calama.className} ${talios.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
