import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local"

const talios =localFont
({
    src: "./talios.otf"
})

const calama =localFont
({
    src: "./calama_new.ttf"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${calama.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
